apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::413510603806:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-11STB1MVH1VWU
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
       - system:masters
      rolearn: arn:aws:iam::413510603806:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-03T07:40:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1463"
  uid: 0d4f0a91-f721-421e-bddb-992ad1ebd17c
