apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::413510603806:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1SN247LJM4KSU
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
       - system:masters
     rolearn: arn:aws:iam::413510603806:role/UdacityFlaskDeployCBKubectlRole
     username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-03T03:26:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2112"
  uid: c8047a7b-e37f-4334-8562-523ecb482e0a
